// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.15.8
// source: proto/drone.proto

package drone

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DroneService_ReportLocation_FullMethodName = "/drone.DroneService/ReportLocation"
)

// DroneServiceClient is the client API for DroneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DroneServiceClient interface {
	// Bi-directional streaming for location updates.
	// Drone sends location, server might send back configuration or ack.
	ReportLocation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LocationRequest, LocationResponse], error)
}

type droneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDroneServiceClient(cc grpc.ClientConnInterface) DroneServiceClient {
	return &droneServiceClient{cc}
}

func (c *droneServiceClient) ReportLocation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LocationRequest, LocationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DroneService_ServiceDesc.Streams[0], DroneService_ReportLocation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LocationRequest, LocationResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DroneService_ReportLocationClient = grpc.BidiStreamingClient[LocationRequest, LocationResponse]

// DroneServiceServer is the server API for DroneService service.
// All implementations must embed UnimplementedDroneServiceServer
// for forward compatibility.
type DroneServiceServer interface {
	// Bi-directional streaming for location updates.
	// Drone sends location, server might send back configuration or ack.
	ReportLocation(grpc.BidiStreamingServer[LocationRequest, LocationResponse]) error
	mustEmbedUnimplementedDroneServiceServer()
}

// UnimplementedDroneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDroneServiceServer struct{}

func (UnimplementedDroneServiceServer) ReportLocation(grpc.BidiStreamingServer[LocationRequest, LocationResponse]) error {
	return status.Error(codes.Unimplemented, "method ReportLocation not implemented")
}
func (UnimplementedDroneServiceServer) mustEmbedUnimplementedDroneServiceServer() {}
func (UnimplementedDroneServiceServer) testEmbeddedByValue()                      {}

// UnsafeDroneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DroneServiceServer will
// result in compilation errors.
type UnsafeDroneServiceServer interface {
	mustEmbedUnimplementedDroneServiceServer()
}

func RegisterDroneServiceServer(s grpc.ServiceRegistrar, srv DroneServiceServer) {
	// If the following call panics, it indicates UnimplementedDroneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DroneService_ServiceDesc, srv)
}

func _DroneService_ReportLocation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DroneServiceServer).ReportLocation(&grpc.GenericServerStream[LocationRequest, LocationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DroneService_ReportLocationServer = grpc.BidiStreamingServer[LocationRequest, LocationResponse]

// DroneService_ServiceDesc is the grpc.ServiceDesc for DroneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DroneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone.DroneService",
	HandlerType: (*DroneServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportLocation",
			Handler:       _DroneService_ReportLocation_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/drone.proto",
}
