

CREATE TABLE drones (
    id VARCHAR(27) PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL CHECK (status IN ('IDLE', 'DELIVERING', 'BROKEN')),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orders (
    id VARCHAR(27) PRIMARY KEY,
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'RESERVED', 'PICKED_UP', 'DELIVERED', 'FAILED')),
    origin_lat DOUBLE PRECISION NOT NULL,
    origin_lon DOUBLE PRECISION NOT NULL,
    dest_lat DOUBLE PRECISION NOT NULL,
    dest_lon DOUBLE PRECISION NOT NULL,
    drone_id VARCHAR(27) REFERENCES drones(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_drones_status ON drones(status);
CREATE INDEX idx_orders_status ON orders(status);
